[cae]
#麦克数
nMicNum = 4

#参考数，可选值：1 2
nRefNum = 2

#主波束索引，可选值：0 1 2 3
# 0:270-360；1:0-90；2:90-180；3:180-270；
nChiefBeam = 1

#麦克风间距，单位米, 是圆的半径，环4当前支持 0.0175 / 0.027 / 0.035 
nMicDist = 0.035

[delay]
#延时估计开关
delay_on = false

[aec]
#aec开关
aec_on = true

#aec调试选项
aec_debug = false

#aec消除等级，可选值：1-5
aec_level = 5

#aec fft长度，可选值：512 1024
aec_fft_size = 512

#参数文件路径
aec_coef = 

[der]
#der开关
der_on = true

#der调试选项
der_debug = false

#der 阶数，可选值10-24（偶数）
nOrder = 20

[post]
#post调试选项
post_debug = false

[agc]
#agc开关
agc_on = true

#agc调试选项
#agc_debug = false

[mlp]
#NN AES开关
aes_on = true

#NN AES调试选项
aes_debug = false

aes_model = ../models/mlp_aes_fsmn_jgjg_20210918.bin

td_on = true
#td_model_type = fsmn
#td_model = ../models/mlp_td_fsmn_hxxj.bin
#td_delay = 2
#td_dynamic = false

#td_model_type = cldnn
#td_model = ../models/mlp_td_cldnn_jgjg_20221209_new_d5.bin
#td_delay = 5
#td_dynamic = false

#mc_td
td_model_type = cldnn_mc
td_dynamic = false
td_delay = 5
td_model = ../models/mlp_mctd_1024_xfxf_xkxk_chxb_xbxb_sxxb_arm.bin

td_mvdr_on = true
